import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'providers/user_provider.dart';
import 'providers/doctor_provider.dart';
import 'providers/admin_provider.dart';
import 'providers/caretaker_provider.dart';
import 'screens/splash_screen.dart';

// If you used "flutterfire configure" to set up Firebase, uncomment these:
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // If you have firebase_options.dart (generated by flutterfire configure):
  //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  //
  // If you added google-services.json / GoogleService-Info.plist manually:
  //   await Firebase.initializeApp();
  //
  // Wrap in try/catch so a bad config doesn't crash before the UI loads:
  try {
    await Firebase.initializeApp();
  } catch (e) {
    // Firebase already initialized (hot restart), or config missing — continue.
  }

  runApp(const MamaCareApp());
}

class MamaCareApp extends StatelessWidget {
  const MamaCareApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => UserProvider()),
        ChangeNotifierProvider(create: (_) => DoctorProvider()),
        ChangeNotifierProvider(create: (_) => AdminProvider()),
        ChangeNotifierProvider(create: (_) => CaretakerProvider()),
      ],
      child: MaterialApp(
        title: 'MamaCare',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFFE8785A),
            primary: const Color(0xFFE8785A),
          ),
          scaffoldBackgroundColor: const Color(0xFFFDF8F5),
          fontFamily: 'Roboto',
          useMaterial3: true,
          appBarTheme: const AppBarTheme(
            backgroundColor: Color(0xFFE8785A),
            foregroundColor: Colors.white,
            elevation: 0,
          ),
        ),
        home: const SplashScreen(),
      ),
    );
  }
}
